spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:
    url: jdbc:postgresql://hxy-zxjy-db.hxy:5432/ai_assistant_db
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
#      host: 127.0.0.1
      host: hxy-zxjy-rds.hxy
      port: 6379
      password:  # 如果有密码，请填写
      database: 0  # 使用的数据库编号，默认是0
      timeout: 5000  # 连接超时时间（毫秒）
      lettuce:
        pool:
          max-active: 8  # 最大活动连接数
          max-wait: -1  # 获取连接的最大等待时间（毫秒），-1表示无限等待
          max-idle: 8  # 最大空闲连接数
          min-idle: 0  # 最小空闲连接数


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: t_
  mapper-locations: classpath:mapper/*.xml,classpath:custom/*.xml


#wx:
#  appId: wx7f269cb65f6eef7a
#  appSecret: e47bd03734db8f262b0a1c052f43e326
#  token: 123456
#  #项目部署服务ip+端口映射地址
#  domain: http://xh7hfq.natappfree.cc
#  #微信用户信息扫码回调地址
#  redirect-uri: /saveUserInfo
#  #微信回复模板ID
#  templateId: 6Zsp3pJJges0BvbFF81pPRX-3wcmAgMmW3vAp8I6koo

wx:
  appId: wx0a971a93b324d491
  appSecret: 61d64c6c7e246aedf9f31d54ae0fc929
  token: 123456
  #项目部署服务ip+端口映射地址
  domain: http://bend7q.natappfree.cc
  #微信用户信息扫码回调地址
  redirect-uri: /saveUserInfo
  #微信回复模板ID
  templateId: 6XNnaa_Qk0OUQ-3g5y15eX_WNQt9GktEfhKRd_eRjQs
